version: '3'

services:
  timeback:
    container_name: timeshift
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        NODE_ENV: production
    image: bakaso/timeshift
    tmpfs:
      - /run
      - /tmp
    environment:
      - URL=${URL}
      - DELAY_HOURS=${DELAY_HOURS}
      - HOST=${HOST}
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - FORMAT=${FORMAT}
      - MOUNTS=${MOUNTS}
